image: node:10-stretch

stages:
  - test
  - release

test:
  stage: test
  except:
    - triggers
  tags:
    - docker
  script:
   - npm i
   - npm install -g grunt-cli
   - npm update
   - grunt

release:
  stage: release
  only:
    - triggers
  script:
    - if [ -z "${VERSION}" ]; then exit 0; fi
    - grunt release:${VERSION}
