before_script:
  - . ~/.nvm/nvm.sh && nvm use 8

stages:
  - test
  - release

test:
  stage: test
  except:
    - triggers
  tags:
    - shell
    - online.net
  script:
   - npm i
   - npm update
   - grunt

release:
  stage: release
  only:
    - triggers
  script:
    - if [ -z "${VERSION}" ]; then exit 0; fi
    - grunt release:${VERSION}